version: '3.8'

services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - tracing

  # OTEL Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter metrics
    depends_on:
      - jaeger
    networks:
      - tracing

  # Redis for examples
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - tracing

  # PostgreSQL for examples
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: gotel_examples
      POSTGRES_USER: gotel
      POSTGRES_PASSWORD: gotel123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tracing

volumes:
  postgres_data:

networks:
  tracing:
    driver: bridge